	playscreen.ofs := VBXE_DATA + 0;
	playscreen.width := 320;
	playscreen.height := 200;

	presents.ofs := VBXE_DATA + 64000;
	presents.width := 320;
	presents.height := 200;

	explosion.ofs := VBXE_DATA + 128000;
	explosion.width := 42;
	explosion.height := 114;

	newvaus.ofs := VBXE_DATA + 132788;
	newvaus.width := 41;
	newvaus.height := 193;

	shinewall.ofs := VBXE_DATA + 140701;
	shinewall.width := 16;
	shinewall.height := 80;

	minivaus.ofs := VBXE_DATA + 141981;
	minivaus.width := 20;
	minivaus.height := 5;

	levelsel.ofs := VBXE_DATA + 142081;
	levelsel.width := 21;
	levelsel.height := 95;

	letters.ofs := VBXE_DATA + 144076;
	letters.width := 128;
	letters.height := 56;

	normal.ofs := VBXE_DATA + 151244;
	normal.width := 32;
	normal.height := 7;

	lasers.ofs := VBXE_DATA + 151468;
	lasers.width := 32;
	lasers.height := 7;

	enlarged.ofs := VBXE_DATA + 151692;
	enlarged.width := 64;
	enlarged.height := 7;

	shoots.ofs := VBXE_DATA + 152140;
	shoots.width := 13;
	shoots.height := 8;

	flux.ofs := VBXE_DATA + 152244;
	flux.width := 8;
	flux.height := 41;

	balldata.ofs := VBXE_DATA + 152572;
	balldata.width := 5;
	balldata.height := 5;

	pattern0.ofs := VBXE_DATA + 152597;
	pattern0.width := 26;
	pattern0.height := 24;

	pattern1.ofs := VBXE_DATA + 153221;
	pattern1.width := 14;
	pattern1.height := 14;

	pattern2.ofs := VBXE_DATA + 153417;
	pattern2.width := 38;
	pattern2.height := 35;

	pattern3.ofs := VBXE_DATA + 154747;
	pattern3.width := 28;
	pattern3.height := 29;

	pattern4.ofs := VBXE_DATA + 155559;
	pattern4.width := 30;
	pattern4.height := 30;
