	explosion.ofs := VBXE_DATA + $00000000;
	explosion.width := 42;
	explosion.height := 114;

	newvaus.ofs := VBXE_DATA + $000012B4;
	newvaus.width := 41;
	newvaus.height := 193;

	shinewall.ofs := VBXE_DATA + $0000319D;
	shinewall.width := 16;
	shinewall.height := 80;

	minivaus.ofs := VBXE_DATA + $0000369D;
	minivaus.width := 20;
	minivaus.height := 5;

	levelsel.ofs := VBXE_DATA + $00003701;
	levelsel.width := 21;
	levelsel.height := 95;

	letters.ofs := VBXE_DATA + $00003ECC;
	letters.width := 128;
	letters.height := 56;

	normal.ofs := VBXE_DATA + $00005ACC;
	normal.width := 32;
	normal.height := 7;

	lasers.ofs := VBXE_DATA + $00005BAC;
	lasers.width := 32;
	lasers.height := 7;

	enlarged.ofs := VBXE_DATA + $00005C8C;
	enlarged.width := 64;
	enlarged.height := 7;

	shoots.ofs := VBXE_DATA + $00005E4C;
	shoots.width := 13;
	shoots.height := 8;

	flux.ofs := VBXE_DATA + $00005EB4;
	flux.width := 8;
	flux.height := 41;

	balldata.ofs := VBXE_DATA + $00005FFC;
	balldata.width := 5;
	balldata.height := 5;

	pattern0.ofs := VBXE_DATA + $00006015;
	pattern0.width := 26;
	pattern0.height := 24;

	pattern1.ofs := VBXE_DATA + $00006285;
	pattern1.width := 14;
	pattern1.height := 14;

	pattern2.ofs := VBXE_DATA + $00006349;
	pattern2.width := 38;
	pattern2.height := 35;

	pattern3.ofs := VBXE_DATA + $0000687B;
	pattern3.width := 28;
	pattern3.height := 29;

	pattern4.ofs := VBXE_DATA + $00006BA7;
	pattern4.width := 30;
	pattern4.height := 30;

	// ofset = VBXE_DATA + $00006F2B
