	presents.ofs := VBXE_DATA + $00000000;
	presents.width := 320;
	presents.height := 200;

	explosion.ofs := VBXE_DATA + $0000FA00;
	explosion.width := 42;
	explosion.height := 114;

	newvaus.ofs := VBXE_DATA + $00010CB4;
	newvaus.width := 41;
	newvaus.height := 193;

	shinewall.ofs := VBXE_DATA + $00012B9D;
	shinewall.width := 16;
	shinewall.height := 80;

	minivaus.ofs := VBXE_DATA + $0001309D;
	minivaus.width := 20;
	minivaus.height := 5;

	levelsel.ofs := VBXE_DATA + $00013101;
	levelsel.width := 21;
	levelsel.height := 95;

	letters.ofs := VBXE_DATA + $000138CC;
	letters.width := 128;
	letters.height := 56;

	normal.ofs := VBXE_DATA + $000154CC;
	normal.width := 32;
	normal.height := 7;

	lasers.ofs := VBXE_DATA + $000155AC;
	lasers.width := 32;
	lasers.height := 7;

	enlarged.ofs := VBXE_DATA + $0001568C;
	enlarged.width := 64;
	enlarged.height := 7;

	shoots.ofs := VBXE_DATA + $0001584C;
	shoots.width := 13;
	shoots.height := 8;

	flux.ofs := VBXE_DATA + $000158B4;
	flux.width := 8;
	flux.height := 41;

	balldata.ofs := VBXE_DATA + $000159FC;
	balldata.width := 5;
	balldata.height := 5;

	pattern0.ofs := VBXE_DATA + $00015A15;
	pattern0.width := 26;
	pattern0.height := 24;

	pattern1.ofs := VBXE_DATA + $00015C85;
	pattern1.width := 14;
	pattern1.height := 14;

	pattern2.ofs := VBXE_DATA + $00015D49;
	pattern2.width := 38;
	pattern2.height := 35;

	pattern3.ofs := VBXE_DATA + $0001627B;
	pattern3.width := 28;
	pattern3.height := 29;

	pattern4.ofs := VBXE_DATA + $000165A7;
	pattern4.width := 30;
	pattern4.height := 30;

	playscreen.ofs := VBXE_DATA + $0001692B;
	playscreen.width := 320;
	playscreen.height := 200;

	// ofset = $0002632B
